package org.esvux.lienzo2D.editor;

import java.awt.Color;

/**
 *
 * @author esvux
 */
public class About extends javax.swing.JDialog {

    /**
     * Creates new form AcercaDe
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setLocation(
            parent.getLocation().x + parent.getWidth() / 2 - this.getWidth() / 2,
            parent.getLocation().y + parent.getHeight()/ 2 - this.getHeight() / 2
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Icono = new javax.swing.JLabel();
        jLabel_Proyecto = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Desarrollador = new javax.swing.JLabel();
        jLabel_Partner = new javax.swing.JLabel();
        jButton_Cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de Lienzos 2D");
        setBackground(java.awt.Color.white);
        setLocationByPlatform(true);
        setResizable(false);

        jLabel_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/esvux/lienzo2D/recursos/iconos/SOL.png"))); // NOI18N

        jLabel_Proyecto.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel_Proyecto.setText("Proyecto 1 de Compiladores 2");

        jLabel_Nombre.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel_Nombre.setText("Lienzos 2D");

        jLabel_Desarrollador.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel_Desarrollador.setText("By: Esvux");

        jLabel_Partner.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel_Partner.setText("Powered by: StackOverLove");

        jButton_Cerrar.setText("Cerrar");
        jButton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Icono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nombre)
                            .addComponent(jLabel_Proyecto)
                            .addComponent(jLabel_Desarrollador)
                            .addComponent(jLabel_Partner))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Proyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Desarrollador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Partner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Cerrar))
                    .addComponent(jLabel_Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cerrar;
    private javax.swing.JLabel jLabel_Desarrollador;
    private javax.swing.JLabel jLabel_Icono;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Partner;
    private javax.swing.JLabel jLabel_Proyecto;
    // End of variables declaration//GEN-END:variables
}
